### ISSUE TITLE
Spec licensing

### ISSUE THREAD

**Issue by ahelwer** [lorin/tla-tortoise-hare#1]
Hello! I am collecting TLA+ specs for the examples repo and am wondering what license these are under, could you please add one when you have time? Thank you!

**Comment by ahelwer** [comment]
Hi @lorin just wondering whether you'd be able to quickly confirm these specs are licensed under MIT or something similarly permissive! Just replying here in this issue will suffice.

**Comment by lorin** [comment]
Hi @ahelwer,

Apologies for not seeing this until now. I just explicitly added an MIT license to this.
